import { appendFileSync, existsSync, mkdirSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { DEFAULT_GUARDRAILS, checkGuardrails } from "../promotion/budget-guardrail";
export const ACTION_GATE_SCHEMA = "marketing-promotion-approval/v1";
export interface PromotionRecord { schema: typeof ACTION_GATE_SCHEMA; approved_by: string; approved_at: string; expires_at?: string; piece_id?: string; campaign_id?: string; evidence_reviewed: string[]; spend_ceiling_usd: number; event: "human_approval"; }
export type LiveAction = "publish" | "ads_activate" | "budget_change" | "artifact_delete";
export interface ActionGateInput { root: string; action: LiveAction; pieceId?: string; campaignId?: string; dailyBudgetUsd?: number; cumulativeSpendUsd?: number; spendCeilingUsd?: number; }
export interface ActionGateResult { ok: boolean; reasons: string[]; record?: PromotionRecord; }
export function promotionsPath(root: string): string { return resolve(root, "data", "promotions.jsonl"); }
function records(root: string): PromotionRecord[] { if (!existsSync(promotionsPath(root))) return []; return readFileSync(promotionsPath(root), "utf8").split(/\r?\n/).filter(Boolean).flatMap((line) => { try { const r = JSON.parse(line) as PromotionRecord; return r.schema === ACTION_GATE_SCHEMA && r.event === "human_approval" ? [r] : []; } catch { return []; } }); }
function matches(r: PromotionRecord, i: ActionGateInput): boolean { const approved = Date.parse(r.approved_at); const expires = r.expires_at ? Date.parse(r.expires_at) : approved + 24 * 60 * 60 * 1000; return Boolean(r.approved_by && Number.isFinite(approved) && Number.isFinite(expires) && expires > Date.now() && r.evidence_reviewed?.length && r.spend_ceiling_usd >= 0 && (!i.pieceId || r.piece_id === i.pieceId) && (!i.campaignId || r.campaign_id === i.campaignId) && (i.spendCeilingUsd === undefined || r.spend_ceiling_usd >= i.spendCeilingUsd)); }
export function checkActionGate(i: ActionGateInput): ActionGateResult { const reasons: string[] = []; if (!i.root) reasons.push("missing project root"); if (i.action === "artifact_delete") reasons.push("outputs are append-only"); if (i.dailyBudgetUsd !== undefined || i.cumulativeSpendUsd !== undefined) { const g = checkGuardrails({ piece_id: i.pieceId ?? i.campaignId ?? "unknown", daily_budget_usd: i.dailyBudgetUsd ?? 0, cumulative_spend_usd: i.cumulativeSpendUsd }, DEFAULT_GUARDRAILS); reasons.push(...g.violations); } const record = records(i.root).find((r) => matches(r, i)); if (!record) reasons.push("no valid human approval in data/promotions.jsonl"); return { ok: reasons.length === 0, reasons, ...(record ? { record } : {}) }; }
export function recordPromotionApproval(root: string, record: Omit<PromotionRecord, "schema" | "event">): string { if (!record.approved_by || !record.approved_at || !record.evidence_reviewed.length || record.spend_ceiling_usd < 0) throw new Error("invalid promotion approval: approver, timestamp, evidence, and spend ceiling are required"); const path = promotionsPath(root); mkdirSync(dirname(path), { recursive: true }); appendFileSync(path, `${JSON.stringify({ schema: ACTION_GATE_SCHEMA, event: "human_approval", ...record })}\n`, "utf8"); return path; }
export function assertActionAllowed(input: ActionGateInput): void { const r = checkActionGate(input); if (!r.ok) throw new Error(`action-gate blocked ${input.action}: ${r.reasons.join("; ")}`); }
