import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
function files(root, dir) { return readdirSync(join(root, dir), { withFileTypes: true }).flatMap((e) => e.isDirectory() ? files(root, join(dir, e.name)) : e.name.endsWith(".ts") ? [join(root, dir, e.name)] : []); }
function unique(values) { return [...new Set(values)]; }
function providerNamesFromSource(text) { return unique([...text.matchAll(/readonly name = "([a-z0-9-]+)"/g)].map((m) => m[1])); }
function extractDodChecks(text) { return unique([...text.matchAll(/- \[ \] (.+)/g)].map((m) => m[1].trim())); }
export function auditClaims(root = process.cwd()) { const errors = []; const claude = readFileSync(join(root, "CLAUDE.md"), "utf8"); const section = claude.split("## Skills Available (planned")[0].split("## Skills Available")[1] ?? ""; const declared = [...section.matchAll(/^- `([^`]+)`/gm)].map((m) => m[1]).filter((n) => !n.includes("<active client>")); const actual = readdirSync(join(root, ".skills"), { withFileTypes: true }).filter((e) => e.isDirectory()).map((e) => e.name); for (const s of declared) if (!existsSync(join(root, ".skills", s, "SKILL.md"))) errors.push(`skill claim missing: ${s}`); for (const s of actual) if (!declared.includes(s)) errors.push(`skill directory not documented: ${s}`); const text = readFileSync(join(root, ".specs/architecture/PROVIDERS.md"), "utf8"); const providers = unique([...text.matchAll(/^\| [^|]+ \| ([a-z0-9-]+)(?: \| [^|]+)? \|/gim)].map((m) => m[1].toLowerCase()).filter((p) => !["provider", "default"].includes(p))); const realText = files(root, "lib/providers").filter((p) => !p.includes("__mocks__")).map((p) => readFileSync(p, "utf8")).join("\n"); const mockText = files(root, "lib/providers/__mocks__").map((p) => readFileSync(p, "utf8")).join("\n"); const realProviders = providerNamesFromSource(realText).filter((p) => !["ollama", "codex"].includes(p)); const mockProviders = providerNamesFromSource(mockText).filter((p) => !["ollama", "codex"].includes(p)); for (const p of providers) { const rx = new RegExp(`(?:name\\s*=\\s*|["'])${p.replace("-", "\\-")}(?:["']|\\s*:)`); if (!rx.test(realText)) errors.push(`provider claim missing real registration: ${p}`); if (!rx.test(mockText)) errors.push(`provider claim missing mock registration: ${p}`); } for (const p of realProviders) if (!providers.includes(p)) errors.push(`provider implementation undocumented in PROVIDERS.md: ${p}`); for (const p of mockProviders) if (!providers.includes(p)) errors.push(`provider mock undocumented in PROVIDERS.md: ${p}`); const env = readFileSync(join(root, ".env.example"), "utf8"); for (const p of files(root, "lib")) for (const n of [...readFileSync(p, "utf8").matchAll(/process\.env\.([A-Z0-9_]+)/g)].map((m) => m[1])) if (!new RegExp(`^${n}=`, "m").test(env)) errors.push(`env claim missing in .env.example: ${n}`); for (const m of claude.matchAll(/(?:scripts|bin)\/[A-Za-z0-9_.-]+\.(?:mjs|py|sh|ts)/g)) if (!existsSync(join(root, m[0]))) errors.push(`documented script missing: ${m[0]}`); const pieceTemplate = readFileSync(join(root, ".specs", "pieces", "piece-template.md"), "utf8"); const dod = extractDodChecks(pieceTemplate); const expected = ["All platform captions present", "Tech specs verified against platform constraints", "Compliance check passed (`pass: true`)", "Watcher gate passed (claims_tag: MEASURED or CANON)"]; for (const item of expected) if (!dod.includes(item)) errors.push(`piece template DoD drift: missing "${item}"`); return errors; }
if (process.argv[1] && import.meta.url === new URL(process.argv[1], "file:").href) {
  const errors = auditClaims(process.argv[2] ?? process.cwd());
  if (errors.length) {
    for (const e of errors) console.error(`claims-audit: FAIL — ${e}`);
    process.exit(1);
  }
  console.log("claims-audit: PASS");
}
