/** Marketing projections over canonical Loop receipts/findings. No ledger or terminal engine lives here. */
import { appendFileSync, existsSync, mkdirSync, openSync, closeSync, readFileSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { createHash, randomUUID } from "node:crypto";

/** Contract-safe manifest id; the product name remains the official `loop.marketing` extension. */
export const EXTENSION_ID = "loop-marketing";
export const EXTENSION_VERSION = "1.0.0";
export type CoreTerminal = "COMPLETE" | "PARTIAL" | "BLOCKED" | "REGRESSED";
export interface DomainReceipt { schema:string; receipt_id:string; receipt_hash:string; run_id:string; task_id:string; stage_id:string; attempt:number; revision:number; actor_id:string; truth_class:string; evidence_refs:string[]; extension:{id:string;version:string;composed_graph_hash:string}; marketing?:{campaign_id?:string;piece_id?:string;channel?:string}; status:string; retry?:number; blocker?:string; output_ref?:string; remote_confirmation?:{confirmed:boolean;ref?:string;checked_at?:string}; created_at:string }
export interface FindingInput { run_id:string; campaign_id?:string; piece_id?:string; stage_id:string; code:string; severity:"low"|"medium"|"high"|"critical"; scope:string; owner_repo:string; summary:string; reproduction:string[]; impact:string; tests:string[]; acceptance_criteria:string[]; evidence_refs?:string[] }
export interface Tracker { upsert(input:{repo:string;fingerprint:string;title:string;body:string;reopen:boolean}):Promise<{confirmed:boolean;ref?:string}>; requery(ref:string):Promise<{confirmed:boolean;state?:string}> }
interface FindingState { fingerprint:string; occurrence_count:number; status:"pending"|"open"|"resolved"|"accepted"; issue_ref?:string; owner_repo:string; last_seen:string; last_error?:string }
interface OutboxRow { id:string; fingerprint:string; input:FindingInput; attempts:number; state:"pending"|"confirmed"; issue_ref?:string; created_at:string }
const now=()=>new Date().toISOString();
const sha=(v:unknown)=>createHash("sha256").update(JSON.stringify(v)).digest("hex");
const base=(root:string)=>resolve(root,".simplicio","marketing-projections");
const files=(root:string)=>({state:join(base(root),"findings.json"),occ:join(base(root),"occurrences.jsonl"),outbox:join(base(root),"outbox.json"),timeline:join(base(root),"timeline.jsonl")});
function read<T>(path:string,fallback:T):T { try{return JSON.parse(readFileSync(path,"utf8")) as T}catch{return fallback} }
function atomic(path:string,value:unknown){mkdirSync(dirname(path),{recursive:true});const tmp=`${path}.${process.pid}.${randomUUID()}.tmp`;writeFileSync(tmp,JSON.stringify(value,null,2));renameSync(tmp,path)}
async function locked<T>(root:string,fn:()=>Promise<T>|T):Promise<T>{const lock=join(base(root),".lock");mkdirSync(dirname(lock),{recursive:true});for(let i=0;i<200;i++){let fd:number|undefined;try{fd=openSync(lock,"wx");return await fn()}catch(e){if((e as NodeJS.ErrnoException).code!=="EEXIST")throw e;await new Promise(r=>setTimeout(r,5))}finally{if(fd!==undefined){closeSync(fd);rmSync(lock,{force:true})}}}throw new Error("marketing projection lock timeout")}

const SECRET=/(?:gh[pousr]_[A-Za-z0-9_]{20,}|sk-[A-Za-z0-9_-]{16,}|(?:api[_-]?key|token|password|authorization)\s*[:=]\s*\S+)/gi;
const EMAIL=/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/gi;
const PHONE=/(?<!\w)(?:\+?\d[\d .()-]{8,}\d)(?!\w)/g;
export function sanitize(value:string):string{return value.replace(SECRET,"[REDACTED_SECRET]").replace(EMAIL,"[REDACTED_EMAIL]").replace(PHONE,"[REDACTED_PHONE]")}
function cleanInput(i:FindingInput):FindingInput{return JSON.parse(sanitize(JSON.stringify(i))) as FindingInput}
export function findingFingerprint(i:FindingInput):string{return sha([i.stage_id,i.code,i.scope,i.owner_repo])}
export function validateDomainReceipt(r:DomainReceipt):string[]{const e:string[]=[];for(const k of ["receipt_id","receipt_hash","run_id","task_id","stage_id","actor_id","truth_class","created_at"] as const)if(!r[k])e.push(`${k} is required`);if(r.schema!=="simplicio.stage-receipt/v1")e.push("canonical stage receipt schema required");if(!Number.isInteger(r.revision)||r.revision<1)e.push("positive revision required");if(!Array.isArray(r.evidence_refs))e.push("evidence_refs array required");if(r.extension?.id!==EXTENSION_ID||r.extension?.version!==EXTENSION_VERSION||!r.extension?.composed_graph_hash)e.push("extension version and composed graph hash required");if(r.remote_confirmation?.confirmed&&!r.remote_confirmation.ref)e.push("confirmed remote effect requires ref");return e}
export function projectReceipt(root:string,r:DomainReceipt):void{const errors=validateDomainReceipt(r);if(errors.length)throw new Error(errors.join("; "));mkdirSync(base(root),{recursive:true});appendFileSync(files(root).timeline,`${JSON.stringify({receipt_id:r.receipt_id,run_id:r.run_id,campaign_id:r.marketing?.campaign_id,piece_id:r.marketing?.piece_id,stage_id:r.stage_id,actor_id:r.actor_id,status:r.status,retry:r.retry??0,blocker:r.blocker??null,output_ref:r.output_ref??null,remote_confirmation:r.remote_confirmation??{confirmed:false},created_at:r.created_at})}\n`)}

export async function collectFinding(root:string,input:FindingInput):Promise<FindingState>{return locked(root,()=>{const safe=cleanInput(input),fp=findingFingerprint(safe),p=files(root),states=read<Record<string,FindingState>>(p.state,{}),out=read<OutboxRow[]>(p.outbox,[]),existing=states[fp],reopen=existing?.status==="resolved";const state:FindingState={...existing,fingerprint:fp,occurrence_count:(existing?.occurrence_count??0)+1,status:reopen?"pending":existing?.status??"pending",owner_repo:safe.owner_repo,last_seen:now()};states[fp]=state;mkdirSync(base(root),{recursive:true});appendFileSync(p.occ,`${JSON.stringify({fingerprint:fp,run_id:safe.run_id,stage_id:safe.stage_id,evidence_refs:safe.evidence_refs??[],observed_at:state.last_seen})}\n`);if(!out.some(x=>x.fingerprint===fp&&x.state==="pending"))out.push({id:randomUUID(),fingerprint:fp,input:safe,attempts:0,state:"pending",created_at:now()});atomic(p.state,states);atomic(p.outbox,out);return state})}
function body(i:FindingInput,fp:string){return sanitize(`## Reproduction\n${i.reproduction.map((x,n)=>`${n+1}. ${x}`).join("\n")}\n\n## Impact\n${i.impact}\n\n## Tests\n${i.tests.map(x=>`- ${x}`).join("\n")}\n\n## Acceptance criteria\n${i.acceptance_criteria.map(x=>`- [ ] ${x}`).join("\n")}\n\nFingerprint: \`${fp}\`\nScope: ${i.scope}`)}
export async function reconcileOutbox(root:string,tracker:Tracker):Promise<{confirmed:number;pending:number}>{return locked(root,async()=>{const p=files(root),states=read<Record<string,FindingState>>(p.state,{}),out=read<OutboxRow[]>(p.outbox,[]);let confirmed=0;for(const row of out.filter(x=>x.state==="pending")){row.attempts++;const s=states[row.fingerprint];try{const r=await tracker.upsert({repo:row.input.owner_repo,fingerprint:row.fingerprint,title:`[marketing finding] ${sanitize(row.input.summary)}`,body:body(row.input,row.fingerprint),reopen:s?.status==="resolved"});if(r.confirmed&&r.ref){row.state="confirmed";row.issue_ref=r.ref;s.status="open";s.issue_ref=r.ref;delete s.last_error;confirmed++}else{s.last_error="tracker returned no remote confirmation"}}catch(e){s.last_error=sanitize(String(e))}}atomic(p.state,states);atomic(p.outbox,out);return{confirmed,pending:out.filter(x=>x.state==="pending").length}})}
export function findingsReport(root:string){const p=files(root),states=Object.values(read<Record<string,FindingState>>(p.state,{})),out=read<OutboxRow[]>(p.outbox,[]);return{schema:"loop.marketing/findings-view/v1",extension:{id:EXTENSION_ID,version:EXTENSION_VERSION},findings:states,pending_outbox:out.filter(x=>x.state==="pending").length}}
export async function auditCompletion(root:string,terminal:CoreTerminal,tracker:Tracker,opts:{reporting_required:boolean;receipts:DomainReceipt[];receipt_ttl_ms?:number}):Promise<{requested_terminal:CoreTerminal;reason:string;revoke_terminal:boolean}>{for(const r of opts.receipts){const e=validateDomainReceipt(r),age=Date.now()-Date.parse(r.created_at);if(!Number.isFinite(age)||age>(opts.receipt_ttl_ms??3_600_000))e.push("receipt is stale");if(e.length)return{requested_terminal:terminal==="COMPLETE"?"REGRESSED":"BLOCKED",reason:`invalid or stale receipt: ${e.join("; ")}`,revoke_terminal:terminal==="COMPLETE"}}const report=findingsReport(root);for(const f of report.findings.filter(x=>x.status==="open"&&x.issue_ref)){const q=await tracker.requery(f.issue_ref!);if(!q.confirmed)return{requested_terminal:terminal==="COMPLETE"?"REGRESSED":"BLOCKED",reason:"remote finding re-query unconfirmed",revoke_terminal:terminal==="COMPLETE"};if(q.state==="closed")f.status="resolved"}const unresolved=report.findings.filter(x=>!(["resolved","accepted"] as string[]).includes(x.status));if(unresolved.length&&(opts.reporting_required||unresolved.some(x=>x.status!=="pending")))return{requested_terminal:terminal==="COMPLETE"?"REGRESSED":"BLOCKED",reason:"in-scope finding is unresolved or untracked",revoke_terminal:terminal==="COMPLETE"};return{requested_terminal:terminal,reason:"marketing specialization accepted core terminal",revoke_terminal:false}}
export function reportingDoctor(root:string){const r=findingsReport(root);return{schema:"loop.marketing/reporting-doctor/v1",ok:r.pending_outbox===0,extension:r.extension,pending_outbox:r.pending_outbox,findings:r.findings.length}}
